#define NERVICI_PREFIX "${CMAKE_INSTALL_PREFIX}"
#define NERVICI_MODS_DIR "/${NERVICI_MODS_DIR}"
#define NERVICI_IMAGES_DIR "/${NERVICI_IMAGES_DIR}"
#define NERVICI_FONTS_DIR "/${NERVICI_FONTS_DIR}"
#define NERVICI_SOUNDS_DIR "/${NERVICI_SOUNDS_DIR}"
#define NERVICI_MUSIC_DIR "/${NERVICI_MUSIC_DIR}"

