SET (FONTS mono.ttf)

SET (DEPS "")

SET (DEPS ${DEPS} ${CMAKE_CURRENT_BINARY_DIR}/${NERVICI_FONTS_DIR})
ADD_CUSTOM_COMMAND (
    OUTPUT ${CMAKE_CURRENT_BINARY_DIR}/${NERVICI_FONTS_DIR}
    COMMAND ${CMAKE_COMMAND} -E make_directory ${CMAKE_CURRENT_BINARY_DIR}/${NERVICI_FONTS_DIR}
    COMMENT "Creating ${NERVICI_FONTS_DIR} directory"
)

FOREACH (font ${FONTS})
    SET (DEPS ${DEPS} ${CMAKE_CURRENT_BINARY_DIR}/${NERVICI_FONTS_DIR}/${font})
    ADD_CUSTOM_COMMAND (
        OUTPUT ${CMAKE_CURRENT_BINARY_DIR}/${NERVICI_FONTS_DIR}/${font}
        COMMAND ${CMAKE_COMMAND} -E copy ${CMAKE_CURRENT_SOURCE_DIR}/fonts/${font} ${CMAKE_CURRENT_BINARY_DIR}/${NERVICI_FONTS_DIR}/${font}
        COMMENT "Copying ${font} into ${NERVICI_FONTS_DIR} directory"
    )
ENDFOREACH (font)

ADD_CUSTOM_TARGET(Fonts ALL
    DEPENDS ${DEPS}
)
