SET (BASIC_IMAGES heart.png semafor.png smile_setting.png)

SET (DEPS "")

SET (DEPS ${DEPS} ${CMAKE_CURRENT_BINARY_DIR}/${NERVICI_IMAGES_DIR})
ADD_CUSTOM_COMMAND (
    OUTPUT ${CMAKE_CURRENT_BINARY_DIR}/${NERVICI_IMAGES_DIR}
    COMMAND ${CMAKE_COMMAND} -E make_directory ${CMAKE_CURRENT_BINARY_DIR}/${NERVICI_IMAGES_DIR}
    COMMENT "Creating ${NERVICI_IMAGES_DIR} directory"
)

FOREACH (image ${BASIC_IMAGES})
    SET (DEPS ${DEPS} ${CMAKE_CURRENT_BINARY_DIR}/${NERVICI_IMAGES_DIR}/${image})
    ADD_CUSTOM_COMMAND (
        OUTPUT ${CMAKE_CURRENT_BINARY_DIR}/${NERVICI_IMAGES_DIR}/${image}
        COMMAND ${CMAKE_COMMAND} -E copy ${CMAKE_CURRENT_SOURCE_DIR}/images/${image} ${CMAKE_CURRENT_BINARY_DIR}/${NERVICI_IMAGES_DIR}/${image}
        COMMENT "Copying ${image} into ${NERVICI_IMAGES_DIR} directory"
    )
ENDFOREACH (image)

ADD_CUSTOM_TARGET(Images ALL
    DEPENDS ${DEPS}
)
